### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by gokceneraslan** [theislab/scvelo#105]
Hi,

I see that there is a little bit of code duplication between scvelo and scanpy like the preprocessing bits (e.g. normalize_per_cell, filter_genes etc.). It'd be great to outsource these to scanpy. Besides, there are some improvements going on in scanpy, for example `normalize_total` is more efficient and faster now and filter_genes_dispersion is replaced with highly_variable_genes which do not subset HVG any more but just flags them.

Cheers!

**Comment by stefanpeidli** [comment]
Hi,
we are (as far as I know) currently working on the intersection between scvelo and scanpy to fix code duplication. We still have some unspliced/spliced specific stuff in our functions though (such as the option to filter by counts shared in both unspliced and spliced simultaneously) and will soon have to figure out what is relevant to scanpy and necessary for scvelo.

**Comment by VolkerBergen** [comment]
I rewrote `normalize_per_cell` in scvelo to speed it up for layers and make it use initial cell sizes (from before filtering). Due to the latter, it can only be replaced, if scanpy's `normalize_total` allows using initial sizes as `target_sum`.

Replacement of `filter_genes_dispersion` with `highly_variable_genes` is already accounted for in all subsequent calls of velocity tools. It's just left to actually replace it for the next release.
