### ISSUE TITLE
latent time opposite to velocity direction

### ISSUE THREAD

**Issue by constantAmateur** [theislab/scvelo#114]
Running scVelo with the dynamic model on a data-set where we know how the cells should be ordered yields very good results in terms of the velocity vectors.

![scvelo_direction](https://user-images.githubusercontent.com/1410525/69559931-c5732e00-0fa2-11ea-96f9-de1cf8c313d4.png)

Our strong expectation is that the biological process should proceed from bottom left up top right.  However, when we infer latent time, the ordering seems to be reversed.  

![scvelo_latent_time](https://user-images.githubusercontent.com/1410525/69560026-f81d2680-0fa2-11ea-9807-2977e1570f25.png)

I'm guessing this is because there is a group of what looks like "root cells" on the left of the blob at the top.  Is it possible to tell scVelo to ignore these cells when calculating latent time?  Can miss-assignment of the root cells produce this kind of inversion?

I've looked at the documentation for `recover_latent_time` and there is a `root_key` parameter but I can't work out how to use it to specify which cells to use/not use.

**Comment by VolkerBergen** [comment]
The reversion indeed comes from falsely assigned root cells, which also gave me quite some headache as this hampers robustness. In particular for smaller cell numbers, this sometimes happens as also 'isolated' cells are classified as root cells since there is no outgoing flow.

We will work out a more robust way of confidently assign root cells soon. For now, you can either store a root cell in `adata.uns['iroot'] and use `root_key='iroot'`, or you can constrain the `adata.obs['root_cells']` to the bottom cells.

**Comment by constantAmateur** [comment]
Thank you, it's good to understand what caused this.  Changing the root as you described worked and the ordering now looks like I expected it to.

![scvelo_new_root](https://user-images.githubusercontent.com/1410525/69630935-4e42a600-1045-11ea-8457-5f4dc0939d98.png)
