### ISSUE TITLE
How to interpret the effect of using latent time as a regularization for velocity?

### ISSUE THREAD

**Issue by GMaciag** [theislab/scvelo#121]
The function `scv.tl.velocity` has the option to *"use latent time as a regularization for velocity when using dynamical mode"*. Can someone explain to me what exactly this is doing, especially from the biological point of view? 

I'm using scvelo to compare two datasets and for one setting the option `use_latent_time=True` changes very little (most of the cells move according with the latent time progression anyway), however, in the second dataset, it makes a huge difference whether I regularise the velocity or not. Most of the graph inverts directionality between the two cases.

Comparing the velocities is a crucial part in my analysis of these two datasets. I have certain expectations, but I wouldn't like to bias myself, especially based on a single parameter that I do not know the biological meaning behind.

**Comment by VolkerBergen** [comment]
It still appears as parameter of the `tl.velocity` module because we were experimenting with feeding latent time back to the dyn. model as a regularization term. Sorry for the confusion, but it is not to be used as we haven't properly tested it yet, which is why it also doesn't appear in the manuscript. I'll remove such parameters to avoid confusion. If however, it fundamentally changes velocities in your case, this most likely has to do with root cells not being uniquely identified, which you can test with `scv.pl.scatter(adata, color='root_cells')`. Making this more robust is very non-trivial and work in progress.
