### ISSUE TITLE
No learned dynamics for some genes

### ISSUE THREAD

**Issue by fbrundu** [theislab/scvelo#129]
Hi @VolkerBergen, thanks for this tool.
I am having trouble understanding why some genes have no learned dynamics in the dynamical model, although they seem to have enough expression.

In the following figure, I am comparing 2 genes (the first and the last) with Mki67 - which appears to have learned dynamics, and velocity plot. Why are they not available for some genes?

![test](https://user-images.githubusercontent.com/697622/71115343-b9dce680-219f-11ea-8c2f-2732df35455f.png)

Thanks

**Comment by stefanpeidli** [comment]
Hi,
did you run `scv.tl.recover_dynamics` with the default arguments? 
Because in that case scVelo only uses the default `var_names='velocity_genes'` and therefore only learns dynamics of so-called velocity genes (to which Mki67 probably belongs to). If you want to learn the dynamics of all genes you could pass the argument `var_names=adata.var_names` to `scv.tl.recover_dynamics` (though that will take longer).

Hope this helps!

**Comment by VolkerBergen** [comment]
Setting var_names='all' runs it on all genes. Per default it preselects via R-squared ('velocity_genes').

**Comment by fbrundu** [comment]
Thanks!
