### ISSUE TITLE
passing an ax induces strange behavior

### ISSUE THREAD

**Issue by falexwolf** [theislab/scvelo#13]
Hi Volker,

sorry for the insufficient example, but depending on whether I pass a `matplotlib.Axes` or not, I get a completely different behavior. Specifically, all colors are removed when passing `ax`.
```
scv.pl.velocity_embedding_grid(adata, basis='umap', ax=pl.figure(figsize=(10, 10)).gca())
```
Not a top prio, but for reference. :wink:

**Comment by falexwolf** [comment]
And setting
```
rcParams['figure.figsize'] = (10, 10)
rcParams['figure.dpi'] = 400
```
doesn't seem to have an effect if passing `ax=None`. It would be nice if default `rcParams` were respected. Hardcoding a figsize into the function call is definitely against matplotlib's, seaborn's and the inherited Scanpy conventions. :wink:

**Comment by falexwolf** [comment]
In addition, why the hard-coded default of `alpha<1`? Again inheriting from `rcParams` would be nicer.

Scanpy solves this whole issue via a `sc.set_figure_params` call that you can do as startup. This calls [`set_rcParams_scanpy`](https://github.com/theislab/scanpy/blob/master/scanpy/plotting/rcmod.py) if `scanpy=True`. Similar functionality exists in seaborn, too.

So, if you have your favorite rcParams values that dictate the default appearance of plots of scvelo, you should set it in there and set all params in the actual function to `None`.

Then, each user can use his or her favorite rcParams (many have them), the Scanpy defaults or the scvelo defaults. :smile:

**Comment by falexwolf** [comment]
The whole background of this: I did a basic clustering and TI analysis in Scanpy, using Louvain clustering, PAGA, annotating clusters with marker genes etc., getting a nice layout by initializing UMAP with PAGA as otherwise some strange overplotting and disconnections occur. 

I know want to see where cells are going using RNA velocity and run scvelo on the same object. In the end, I'd like an embedding that looks exactly like the `sc.pl.umap` plot, colored by different annotations with given, user-chosen colormaps/palettes that are stored in the adata. But now of course, I want the arrows on top of it. It's pretty close to that already, but there are still some inconsistencies.

**Comment by VolkerBergen** [comment]
That surely has to be done properly as you mention. I have not thought over that in detail yet mainly because I wanted to have different default figsize and dpi for different plots -  since you won't see much of the single cell velocities in a small figure. I'll most likely do it as been resolved in scanpy.

Btw you can also directly pass figsize and dpi
`scv.pl.velocity_embedding_grid(adata, basis='umap', figsize=(10,10), dpi=150)`.

"Specifically, all colors are removed when passing `ax`." 
Is that from the released version or the latest Github?

**Comment by falexwolf** [comment]
Yes, I used the latest GitHub version.

And yes, it's nice to have a `figsize` argument (I'm using it), but the point was that it should default to `None` and read from `rcParams`, which you can give a `scvelo` flavor; but that should be up to the user. ;)

**Comment by VolkerBergen** [comment]
It's all incorporated in the latest commits. Let me know whether something is missing that would be useful along these lines.

`set_figure_params(style="scvelo")` uses the same defaults as scanpy, only figsize is a slightly larger, fontsize slightly smaller, frameon is False (because most scvelo figs axes are just the embedding coord.) and verbosity is 3 (as the logging is helpful for the user when using a new tool). Alpha in the grid embedding is defaulted to 0.2 because the quivers would not be clearly visible with default 1. Finally, point size is adjusted, so that it accounts for the number of cells while still staying in a range of reasonable values (the latter I found to not always be the case in scanpy).
