### ISSUE TITLE
Computing Latent time

### ISSUE THREAD

**Issue by Jpbernal888** [theislab/scvelo#157]
Hello,

First, I would like to thank you for the nice paper and tool, I find it amazing how simple ideas (not necessarily easy to think of), can result in such a different and powerful way of looking at cellular differentiation. On top of that, I really like the way your code is written.
 
I have two questions related to the computation of the latent time:

1. In the case the root_key hasn't been found beforehand, _i.e._, the else in the code below, and assuming there is more than 1 root candidate; the `root_time` code is overwriting the existing time `t`, so, in every cycle of the for loop, the time used to compute the new root-centered time, is the time computed after the previous reordering. And, taking into account that the function `root_time` is not commutative, I can't really understand the choice of using the previous time instead of using a copy of the original time to calculate the root-centered times.

2. My second doubt is about the `root_time` function itself. I have understood that the function "recenters" the time in the root cell time. What you want to calculate are the gene-specific time increments, then you subtract the root gene time from the gene times that are after the root time. What is not completely clear to me is what you do with the times that are before the root time, you just relocate those times right after all the other times. I kind of see this as a penalization for being before the root cell, is this somehow correct? Or what is the actual idea behind this procedure?

```python
    if root_key in adata.uns.keys():
        root = adata.uns[root_key]
        t, t_ = root_time(t, root=root)
        latent_time = compute_shared_time(t)
    else:
        roots = roots[:4]
        latent_time = np.ones(shape=(len(roots), adata.n_obs))
        for i, root in enumerate(roots):
            t, t_ = root_time(t, root=root)
            latent_time[i] = compute_shared_time(t)
        latent_time = np.mean(latent_time, axis=0)
        latent_time /= np.max(latent_time)
```

**Comment by VolkerBergen** [comment]
Hi @Jpbernal888,

thanks for the kind feedback and pardon the late reply.

The roots may have already been computed e.g. via `tl.terminal_states` or given by the user via `adata.uns[root_key]`, otherwise it is computed here internally. Since there might be several candidates for root cells, it takes the 4 (arbitrary number) most likely root cells and computes a latent time from each, then averages them (just for slightly improved robustness). 

1. It's not overwritten, but added to the list `latent_time`, which is then later simply averaged.
2. That's correct. It's simply recentering all gene-wise time assignments to then couple those to an overall latent time. The main part happens in `compute_shared_time`. There is also a confidence score assigned that takes care of cells that are very close to the rooted cell and may be ambiguous (up- or down-regulation).

After all, the latent time computation is rather simple and there will be quite some room for generalization and improvement. But for now, it seems to be quite insightful and reliable.
