### ISSUE TITLE
Velocity genes between models

### ISSUE THREAD

**Issue by juhaa** [theislab/scvelo#158]
Hi,

After running `scv.tl.velocity`, I noticed that the amount of velocity genes identified with deterministic model is less than when fitting the dynamical model. I understood that by default, both use `min_r2`threshold to define velocity genes, but in the dynamical model more filters are used. Inspecting the code, I don't see why the amount of velocity genes could be less than what you get from the deterministic model:
https://github.com/theislab/scvelo/blob/384543ab7b7171132ecd6faee347ef3c099b50b9/scvelo/tools/velocity.py#L205-L217
You can see the differences in this example:
```
>>> import scvelo as scv
>>> scv.logging.print_version()
Running scvelo 0.1.26.dev20+g384543a (python 3.6.10) on 2020-02-17 16:03.
>>> scv.settings.verbosity = 0
>>> adata = scv.datasets.dentategyrus()
>>> scv.pp.filter_and_normalize(adata, min_shared_counts=30, n_top_genes=2000)
>>> scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
>>> scv.tl.recover_dynamics(adata)
>>> adata_dyn = adata.copy()
>>> scv.tl.velocity(adata_dyn, mode='dynamical', filter_genes=True)
>>> adata_sto = adata.copy()
>>> scv.tl.velocity(adata_sto, mode='stochastic', filter_genes=True)
>>> adata_det = adata.copy()
>>> scv.tl.velocity(adata_det, mode='deterministic', filter_genes=True)
>>> adata_det.var['velocity_genes'].sum()
519
>>> adata_dyn.var['velocity_genes'].sum()
798
```
Am I missing something here or a bug in the code?

Also noticed genes are not actually filtered when `mode='deterministic'` and `filter_genes=True`, and 'velocity_genes' column is not added when `mode='stochastic'` and `filter_genes=True` (the latter being just a matter of consistency, doesn't really affect anything I guess).
```
>>> adata.shape
(2930, 2000)
>>> adata_det.shape
(2930, 519)
>>> adata_dyn.shape
(2930, 2000)
```

**Comment by VolkerBergen** [comment]
Filtering does not have any affect, because for projection only 'velocity_genes' are used anyway (it is just to save memory). The attribute 'velocity_genes' is only added to `adata` when at least one gene has not been classified as 'velocity_gene', otherwise the information is redundant. That is why it is not added when setting `mode='stochastic'` and `filter_genes=True`.
The dynamical velocities were added later, which is why the filtering has not been implemented yet. Would be one-line to add, which I'll do for the next release. However, as said, that has no affect on any downstream results.

The reason for having more genes being classified as velocity_genes by the dynamical model is simply because the r-squared in computed on all data instead of extreme quantiles.

**Comment by juhaa** [comment]
Understood. Thank you for the clarification!
