### ISSUE TITLE
error from scv.pp.moments(adata)

### ISSUE THREAD

**Issue by PattF** [theislab/scvelo#16]
Hi,
I'm attempting to run a scanpy processed .h5ad file through scvelo but am running into the error pasted below.
I'm relatively new to the whole scene, any help is much appreciated. Let me know if you need to see any other info from the attempted run, cheers!
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-5e6c0c5149c1> in <module>()
----> 1 scv.pp.moments(adata)

~\Anaconda3\lib\site-packages\scvelo\preprocessing\moments.py in moments(data, n_neighbors, n_pcs, mode, use_rep, recurse_neighbors, renormalize, plot, copy)
     58 
     59     logg.info('computing moments based on ' + str(mode), r=True)
---> 60     normalize_layers(adata)
     61 
     62     connectivities = get_connectivities(adata, mode, recurse_neighbors=recurse_neighbors)

~\Anaconda3\lib\site-packages\scvelo\preprocessing\utils.py in normalize_layers(data, layers, by_total_size, max_proportion_per_cell, copy)
    273 
    274     for layer in layers:
--> 275         if not_normalized_yet(adata, layer):
    276             counts_per_cell = get_initial_size(adata, layer, by_total_size)
    277             if max_proportion_per_cell is not None and (0 < max_proportion_per_cell < 1):

~\Anaconda3\lib\site-packages\scvelo\preprocessing\utils.py in not_normalized_yet(adata, layer)
    269 
    270     def not_normalized_yet(adata, layer):
--> 271         X = adata.layers[layer]
    272         return np.allclose((X.data[:10] if issparse(X) else X[0]) % 1, 0, atol=1e-3)
    273 

~\Anaconda3\lib\site-packages\anndata\layers.py in __getitem__(self, key)
     43             return self._adata_ref.layers[key][self._oidx, self._vidx]
     44         else:
---> 45             return self._layers[key]
     46 
     47     def __setitem__(self, key, value):

KeyError: 'unspliced'

**Comment by stefanpeidli** [comment]
Hi,

it seems like your Anndata object `adata` has no layer `'unspliced'` containing information about the unspliced RNA. Scvelo needs this [layer](https://anndata.readthedocs.io/en/latest/anndata.AnnData.layers.html) in order to compute the velocities.

You could try and check manually via running the code
`adata.layers['unspliced']`
for your adata and see if your adata has indeed no such layer. Maybe your .h5ad file did not include information about unspliced RNA?

**Comment by stefanpeidli** [comment]
Try running
`adata.layers.keys()`
This should show you the names of all the layers of your adata object. Also check if those layers are empty.

Yes, I think that would be good to check. You could take a look at the layers directly after importing your data using [scanpy's read functions](https://scanpy.readthedocs.io/en/latest/api/index.html#reading). If the code line above still then shows no layers at all (or just empty layers), you should check if your data might be corrupted. Also, which read function are you currently using to import your data?
Apart from that you should also check if you are using up-to-date versions of both scanpy and scvelo, to eliminate that as error source as well.

Hope it helps!

**Comment by stefanpeidli** [comment]
My strongest guess would be that your data file is either corrupted or not containing the necessary informations. You could try to check if you can find the spliced/unspliced informations somewhere else (in some extra annotation file). If you find them (maybe they are saved in a place they do not belong to), you could feed them into the adata object manually.
From the scanpy documentation:

> Note: For reading annotation use pandas.read_… and add it to your AnnData object. The following read functions are intended for the numeric data in the data matrix X.

Maybe you are missing the annotations containing that part of the data?

**Comment by PattF** [comment]
I think I understand what you mean, so possibly how the raw data was mapped initially might not contain the annotations for spliced / unspliced information?

**Comment by stefanpeidli** [comment]
Exactly. 
If you are able to obtain those annotations belonging to your .h5ad file, you can add them with 
`import pandas as pd`
`anno = pd.read_csv(filename_sample_annotation)`
`adata.uns['spliced'] = anno['spliced']`
`adata.obs['unspliced'] = anno['unspliced']`

Otherwise, if you have no such file and as it seems no annotations within your .h5ad file, the necessary information on un/spliced mRNA is missing (mRNA velocity is the derivative of unspliced to spliced mRNA Abundance. scVelo tries to estimate this derivative using the abundances given). Thus mRNA velocity estimation will not work here.

**Comment by VolkerBergen** [comment]
May I ask you whether you have already run the counting pipeline (since the count matrices seem to be missing for you)? http://velocyto.org/velocyto.py/tutorial/cli.html would do that for you generating a loom file, which can then be read into an AnnData object.

**Comment by VolkerBergen** [comment]
@PattF: Were you able to obtain the unspliced/spliced counts? Let me know how I can help.

**Comment by grimwoo** [comment]
@VolkerBergen Sorry to bother you. 
I exported the loom file from Seurat and want to get the RNA velocity. By running "```adata.layers.keys()```", I got "```KeysView(Layers with keys: norm_data, scale_data)
```". According to your suggestion "May I ask you whether you have already run the counting pipeline (since the count matrices seem to be missing for you)?".  It seems scvelo also need velocyto to process the data. Am I right?

**Comment by VolkerBergen** [comment]
Hi Grim,
yes, you'd need to run the counting pipeline beforehand to generate spliced and unspliced count matrices, either with velocyto, loompy or kallisto, see https://scvelo.readthedocs.io/getting_started.html#alignment.

**Comment by grimwoo** [comment]
Thank you so much!




在 Volker Bergen <notifications@github.com>，2020年1月9日 下午6:08写道：

Hi Grim,
yes, you'd need to run the counting pipeline beforehand to generate spliced and unspliced count matrices, either with velocyto, loompy or kallisto, see https://scvelo.readthedocs.io/getting_started.html#alignment.
