### ISSUE TITLE
How to perform differential test on velocity estimation results

### ISSUE THREAD

**Issue by ziyangliu93** [theislab/scvelo#164]
Hi, thanks for the nice tool. I have a tricky problem that remains unsolved. I have a single cell data generated from 10X and I processed the data by Seurat package. After the UMAP visualization, my cells can be separated into 2 clusters. The phenotype that I am interested in is actually the expression of one specific gene, aka, that one gene can group cells into two different states, for instance TP53 gene positive and TP53 gene negative cells. My assumption is that the negative cells  will transform into positive ones and your tools actually revealed the concordant results. However,  these two states were actually intimately mixed within each clusters, and these two clusters have their own velocity, even though the transition pattern is the same. My question is that how can I perform differential test on this type of data after estimation of velocity.

**Comment by VolkerBergen** [comment]
You can run a DE test on expression via scanpy's `sc.tl.rank_genes_groups(adata, groupby='clusters')` or on velocity expression via `scv.tl.rank_velocity_genes(adata, groupby='clusters')`, where groupby would specify the two clusters you want to compare against each other. I'd assume in the former TP53 should then pop up. The projected velocities will show the average directionality. If TP53 is the most dominant driver, it may mask smaller within-cluster velocities. If that is the case and you are rather interested in directionality within each cluster, you may want to perform velocity analysis on each cluster separately.

**Comment by ziyangliu93** [comment]
Thank you for your reply, and I shall attach the figure so that you can better understand the situation I encountered. As you can see from the figure, UMAP projection did physically separate cells into two clusters, but each part actually comprised at least 2 'Seurat clusters', and the cells expressing that specific gene were mixed quite well. To be honest, from the analysis result, the transition states did not always go from negative ones to positive ones but this state was actually 'ground true' state and I think scVelo have done its best. I tried to perform DE test between negative cells and positive cells, how can I do that。

![Screen](https://user-images.githubusercontent.com/56216230/75771749-903a6100-5d85-11ea-8b76-57115aacd22e.gif)

**Comment by adsalas** [comment]
Hi, @VolkerBergen  I think I have a related question but I am not so sure if you answered it with your post because if I got it right it seems that with the options you proposed one could compare the velocity but in regard to specific genes. 
In my case I performed the scvelo analysis on a data set where I have 2 different conditions (control vs KO) and I would like to compare the velocity in specific clusters in a way that I can check if the cells in one of the conditions are "faster" than cells in the other condition. Is there a way to compute that comparison? And if so which would be the variable that can give more useful information regarding the "speed", would it be the velocity length?
I appreciate any help you can provide.

**Comment by adsalas** [comment]
Hi, @VolkerBergen  I think I have a related question but I am not so sure if you answered it with your post because if I got it right it seems that with the options you proposed one could compare the velocity but in regard to specific genes. 
In my case I performed the scvelo analysis on a data set where I have 2 different conditions (control vs KO) and I would like to compare the velocity in specific clusters in a way that I can check if the cells in one of the conditions are "faster" than cells in the other condition. Is there a way to compute that comparison? And if so which would be the variable that can give more useful information regarding the "speed", would it be the velocity length?
I appreciate any help you can provide regarding my question.

**Comment by GabrielBaldissera** [comment]
I'm currently implementing this analysis in my data and I have the same question and conditions ( control and KO). 

I would like to test the velocities by comparing cells from distinct genotypes. It would be really cool to do something like sc.tl.rank_genes_groups(adata, groupby='clusters_genotype'), like cluster3_wt vs cluster3_KO. However, I am not sure if doing a joint analysis of two samples would be correct when one of the samples is from a perturbation study. 
Would you suggest that I should do two distinct analysis and visually try to find differences in the trajectories? 

Best,
Gabriel

**Comment by vbarrera** [comment]
Hi.
First of all and as many others have said before, thanks for the tool.

I'm adding this as a comment but, please, let me know if you prefer it as a new issue to track it more easily.

As the author of the main post, I'm interested in testing the velocity for a given cluster between two conditions (i.e: KO vs control).

When the issue was closed, more than a year ago, the functionality was not implemented. I was wondering if any work has been done on this. I've checked other issues and updates and I haven't found it but I might have missed it. 

As it has been suggested, I'm thinking about extracting the velocity length value and use t-test between conditions. However, in that case, is it better to process the samples together or separately before the t-test? As there is some model fitting and normalization, I think they should be process together and with the sample origin information, separate and test but I'd like confirmation for this (in case the obtained velocity values are independent).

Thanks a lot for your time on the tool and answering all the issues.

Best,

**Comment by RoganGrant** [comment]
@vbarrera did you ever find a working solution here? I (and presumably many others) am interested in doing the same for my data.
