### ISSUE TITLE
The direction of velocity_graph?

### ISSUE THREAD

**Issue by ziyangliu93** [theislab/scvelo#165]
Is there a direction of velocity_graph?

**Comment by VolkerBergen** [comment]
Yes, the graph is directed. PI_ij indicates the transition from cell i to cell j, see https://scvelo.org/scvelo.tl.velocity_graph.html. 

When plotting the full cell-to-cell velocity graph, by default no arrows are shown because there are too many. These can be shown for a particular cell type with `pl.velocity_graph(adata, arrows=True, groups='cluster_name')`.

**Comment by ziyangliu93** [comment]
Thank you for your quick reply, but I could not find any parameters related to setting arrows.

**Comment by VolkerBergen** [comment]
directed and weighted cell-to-cell transitions are stored in `adata.uns['velocity_graph']`. 
For plotting, the `arrows` parameter is only available in the latest version, which you'd need to install via `pip install git+https://github.com/theislab/scvelo`.

**Comment by VolkerBergen** [comment]
Pardon, you're right. Just forgot to push the changes. Now it's available. The arrows are drawn by `igraph` which does not allow to adjust for arrow sizes, unfortunately. So, you will need to set the `groups` parameters to constrain to a specific cluster.

**Comment by VolkerBergen** [comment]
Just saw that `networkx` are currently reimplementing the edge drawing, which then allows the user to pass the `arrowsize` as well. Will update it here, once they release the changes.

**Comment by VolkerBergen** [comment]
Was a quick fix. You can now pass arrowsize as well. Let me know, if that works for you.

**Comment by ziyangliu93** [comment]
Thank you for your help, after installation of the latest release, I can set arrow size of the velocity_graph now.
