### ISSUE TITLE
Hematopoiesis velocity directionality 

### ISSUE THREAD

**Issue by AMA111** [theislab/scvelo#173]
Hey Volker, 

I have a question regarding an analysis of Bone Marrow stem and progenitors compartment from heathy human samples.  

![image](https://user-images.githubusercontent.com/29317258/77174617-a0f71080-6ac1-11ea-8288-f55b4c964a5c.png)

The Figure her shows that there is a developmental process directed from the Erythroid prog (green color) to the Hematopietic stem cells (HSCs in Red color). We already know from previous studies of the Hematopietic system that the development is rather the other way around (From the stem to the prog). 

## Code: Compute velocity and velocity graph
scv.tl.recover_dynamics(sub_data)
scv.tl.velocity(sub_data, mode='dynamical')
scv.tl.velocity_graph(sub_data)
scv.tl.recover_latent_time(sub_data)

I tried also the steady-state model and gave the same conclusions. Also, I I tried the same to other samples from disease states and gave the same result! 

Do you have an idea about the reverse directionality here? Possibly, there is dedifferentiation process is going on, but before we go to this conclusion, I would like to know your opinion. 

Best,
Abdelrahman Mahmoud 
DKFZ

**Comment by VolkerBergen** [comment]
Hi Abdelrahman,

great, that you examine this carefully before drawing any conclusions.

Looking into the phase potraits of top likelihood genes would certainly help.
```
top_genes = adata.var.sort_values('fit_likelihood', ascending=False).index[:10]
scv.pl.scatter(adata, basis=top_genes)
```
If you send me the output, I can help you with interpretations.

**Comment by AMA111** [comment]
Hey Volker, Sure!

![image](https://user-images.githubusercontent.com/29317258/77178828-eddde580-6ac7-11ea-922c-37abc9aff548.png)

**Comment by VolkerBergen** [comment]
Looks like the velocities are mostly driven by the Hemoglobin Beta genes.

Can you also color it with pseudotime / latent time coord. to see the diffs. in the erythroid compartment? What do you expect for HBB towards maturation?

**Comment by AMA111** [comment]
Latent time :

![image](https://user-images.githubusercontent.com/29317258/77184432-22ee3600-6ad0-11ea-9dcc-8fb683dce75e.png)

Pseudotime :
![image](https://user-images.githubusercontent.com/29317258/77184457-2aadda80-6ad0-11ea-822b-dc37d6f9c398.png)

UMAP:
![image](https://user-images.githubusercontent.com/29317258/77184722-7bbdce80-6ad0-11ea-8923-647536783ca3.png)


yes, in the hematopiotic system, we expect maturation steps from: HSCs >> Erythroid prog >> mature Erythroid cells (mostly express hemoglobin related genes)

**Comment by VolkerBergen** [comment]
We analysed one of our datasets today, which also includes erythroid cells. Interestingly, with RNA velocity we obtain directional flows in accordance with biol. expectations in all cell types except for erythroids. It turned out in our example that splicing efficiency seems to change dramatically in erythroids, decreasing the fractions of unspliced counts by half. That could be a reason for 'false' signal.

You could get an indication of such with the following code.
```
counts_s = scv.utils.sum_var(adata.layers['spliced'])
counts_u = scv.utils.sum_var(adata.layers['unspliced'])
fractions_u = counts_u / (counts_s + counts_u)
scv.pl.scatter(adata, color=fractions_u, smooth=True)
```
Would be very interesting to see whether the fractions are gradually decreasing in your erythroid progenitors.

**Comment by AMA111** [comment]
Interesting!! I calculated the fractions from my data and here is how it looks like: 

<img width="722" alt="Screenshot 2020-03-23 at 18 59 03" src="https://user-images.githubusercontent.com/29317258/77347755-9d20f380-6d38-11ea-9907-5f2d08ee9bfc.png">
Do you have  possible explanation for such velocities specially in the Erthroid prog? would be great if you could send me the velocities figures of your dataset? I am interested to see how the overall velocities behaviour in the stem and progenitors other than my data;  since I couldn't find any published example from the BM hematopiotic system with velocities analysis.

**Comment by VolkerBergen** [comment]
Indeed, there is now hundreds of papers making use of RNA velocity, yet (nearly) none of them on hematopoiesis. And I think the reason is because it usually does not comply with the biology.  Conspicuously always observed in blood development, while it works just fine in almost all other systems (under some assumptions). Your example perfectly resembles what I also see in our data.  The significant change in splicing efficiency eventually yields false signal, as illustrated by the dynamics of Hbb gene: It is up-regulated. However, due to a gradual increase in the splicing rate, the curvature in phase space may be turned such that it indicates down-regulation. That violates the fundamental assumption of any RNA velocity framework potentially making it inapplicable. I'll have some thoughts, on whether it can be adapted to changing splicing efficiency.

**Comment by AMA111** [comment]
Great! I  found that it's known in the HSCs biology that they retain more of the unspliced mRNA and get more spliced form **under activation**: https://stemcellsjournals.onlinelibrary.wiley.com/doi/full/10.1634/stemcells.2005-0552. 
Possibly, the Stem cells has undefined  state of uncommitted cells for certain state/fate (reflected by high unspliced fraction), then further through the development state, start to have more spliced forms which would have a critical role for fate commitment. I would be happy to discuss this further and please let me know by any further updates regarding this issue. Thanks Volker!

Best wishes,
Abdelrahman

**Comment by ftheis** [comment]
This is really interesting - so far my assumption always was that hematopoietic kinetics in particular in HSCs and further up are so much slower than the usual kinetics (more weeks than days) that we do not find much. Hence, as Volker said, no real RNA velocity appl in blood. Do you guys see this effect only in erythroids (where transcription could go down etc as well) or also in other downstream cell types?

**Comment by AMA111** [comment]
I think specially in the erythroid prog, the system needs to be very fast to fit the Erythroid cells (RBCs) production rate (~2.4 Million cell/sec) which is very high demand per day. It make sense that the system will increase the splicing rate dramatically at this stage to commit to certain fate > RBCs. Also, I looked at the cell cycle and it seems that the they are high cycling cells (S and G2M) which interestingly fits this paper: https://www.ncbi.nlm.nih.gov/pubmed/30463007 . 
From my point of view, the velocities accurately detected that there is a development process (_False direction as we think_) going on from Eryth prog to MK prog. The issue here is the "direction", but from an optimistic point of view it capture the developmental process correctly :)) 

![Screenshot 2020-03-25 at 12 24 42](https://user-images.githubusercontent.com/29317258/77531724-af637480-6e93-11ea-8122-c058ef9853d3.png)

Can you please explain for me from a method perspective how it capture the directionality? I see that HBB is possibly in a repression phase but this doesn't help me to understand the directionality here?

**Comment by VolkerBergen** [comment]
![SCB_scVelo](https://user-images.githubusercontent.com/31883718/78002297-4c605a80-7337-11ea-8c25-7d19d31adee6.gif)
The directionality is already depicted in gene-wise dynamics by assignment of positive or negative velocities (induction/repression). The projected velocity vector summarizes all gene-wise velocities, whereas in your example we can presume that it is mainly driven by HBB. HBB is picked up as repression (even though it may be induction, thus potentially false signal), which implies that cells should move from the highly expressed to the lowly expressed, i.e. from yellow to blue (colored by velocity pseudotime). 

Good that you mention the cycle effects - same in our data (for Erythroid prog.)! That could also be a cause for false signal (if the cycle cannot be resolved by embedding coord. due to compositional effects of cycle and dev. progression) and should be investigated. Perhaps, you could try [regressing out cycle effects](https://icb-scanpy.readthedocs-hosted.com/en/stable/api/scanpy.pp.regress_out.html). 

Can you also show the phase potraits of HBB on raw data with `scv.pl.scatter(adata, basis='HBB', use_raw=True)`?

**Comment by AMA111** [comment]
I don't recommend regressing out cell cycle, since it's reflecting important underlaying process of the hematopoiesis differentiation. Have you tried to regress out the cell cycle in your data? and do you see change in directionality?

sure!
![Screenshot 2020-03-31 at 14 39 07](https://user-images.githubusercontent.com/29317258/78027284-6a40b600-735d-11ea-94c2-ae473f9730bb.png)

**Comment by ogilliam** [comment]
Hi Volker,


I am facing the same issues as @AMA111. We are using a mouse model of the intestinal crypt in order to investigate cell differentiation. 

![image](https://user-images.githubusercontent.com/64959701/81927879-aca81480-95e4-11ea-9673-f2674b673133.png)


From our biological understanding the arrows in the paneth cells should be pointing the other way around. Differentiation starts in the stem cells and terminates in the different celltypes (Enterocytes, Gobblet cells and Paneth cells). There is some knowledge about dedifferentiation of Paneth cells, but we didn’t expect to observe the majority of arrows pointing in the inverse direction of differentiation.  

Top 10 putative driver genes
![image](https://user-images.githubusercontent.com/64959701/81927930-bfbae480-95e4-11ea-941e-49a7426a3b04.png)


Fraction of unspliced RNA
![image](https://user-images.githubusercontent.com/64959701/81927969-cf3a2d80-95e4-11ea-9099-132f70986238.png)

This left me with the assumption, that a change in splicing efficiency could be the reason for my observation. Does this makes sense or am I missing something here?  
And if this is the reason, would you have any suggestion on how to solve this issue? 


Also, we tested for the number of cells and velocity genes, which looked fine to me:
` print(adata.var['velocity_genes'].sum(), adata.n_vars, adata.n_obs)`
401 3000 5412


Thanks a lot for your help!

Best wishes, 
Oliver

**Comment by VolkerBergen** [comment]
Your genes are undoubtedly supporting directionality from stem to enterocytes. 
However, for paneth cells you got some interesting effects. In _Gm0104_, the red-highlighted part imho does not really fit to the remaining kinetic, thus induces some signal for down-regulation towards stem, which seems to be artificial imho given that the change in unspliced counts is too sudden/rapid..

![image](https://user-images.githubusercontent.com/31883718/81934496-542a4480-95ef-11ea-9af6-db204ce7c240.png)

**Comment by VolkerBergen** [comment]
You seem to get this consistently for 'Gm*' genes. Any clue, whether there's anything specific to those genes?

**Comment by ogilliam** [comment]
Thank you for the quick response! 

Indeed, all the Gm* genes show similar results. 
In intestine, these genes are exclusively expressed in paneth cells.

![image](https://user-images.githubusercontent.com/64959701/82057146-36c6aa80-96c3-11ea-9d98-53cf2011c42a.png)

It seems, that with further differentiation of paneth cells, the expression of GM10104 is also increasing. I am just a bit confused why the scatter plot is indicating the opposite?
Could the splicing efficiency have any effect in this? 

(Gm10104 (DEFA25) belongs to the family of alpha defensins. 
The respective proteins play an important role in the regulation of the microbial flora and the innate immune response against pathogens)

**Comment by ogilliam** [comment]
Hi Volker, 

I reanalyzed the dataset with the updated version of scVelo (0.2.1) and could observe a very low fraction of unspliced counts over the whole dataset, especially low for Paneth cells (Cluster 7, 8, 10, 17). 

![image](https://user-images.githubusercontent.com/64959701/86221869-c2b66800-bb85-11ea-85f0-61955c03b7f4.png)

![image](https://user-images.githubusercontent.com/64959701/86221900-cd70fd00-bb85-11ea-9f4e-90b0f6dcddd5.png)

![image](https://user-images.githubusercontent.com/64959701/86221920-d2ce4780-bb85-11ea-89ae-0e623c919dd9.png)

According to the scVelo website, between 25 - 10%  unspliced counts is expected. Are the 10% a lower threshold or is it possible to analyze datasets with less than 10% unspliced RNA, like in my case? 

Also, I was wondering what the reason for the low fraction of unspliced RNA might be. In this context I found this preprint:


![image](https://user-images.githubusercontent.com/64959701/86222469-918a6780-bb86-11ea-9d64-7b61b8265e91.png)
https://www.biorxiv.org/content/10.1101/2020.03.13.990069v1.full

 
According to the paper, different preprocessing methods create different overall results. Is this something you observed as well? 
For my analysis, I used velocyto.py with the run10X command. 


Thanks a lot!

**Comment by WeilerP** [comment]
@ogilliam
> According to the scVelo website, between 25 - 10% unspliced counts is expected. Are the 10% a lower threshold or is it possible to analyze datasets with less than 10% unspliced RNA, like in my case?

It seems rather low. This should result in a lot of genes being filtered out (based on shared counts). You would have to look at your phase portraits to see if enough information is given to infer dynamics.

> Also, I was wondering what the reason for the low fraction of unspliced RNA might be. In this context I found this preprint:
> 
> ![image](https://user-images.githubusercontent.com/64959701/86222469-918a6780-bb86-11ea-9d64-7b61b8265e91.png)
> https://www.biorxiv.org/content/10.1101/2020.03.13.990069v1.full
> 
> According to the paper, different preprocessing methods create different overall results. Is this something you observed as well?

I did not read the paper but yes, preprocessing does matter!

**Comment by cimbusch** [comment]
In case somebody is interested or bumps into this:

Coordinated changes in gene expression kinetics underlie both mouse and human erythroid maturation
https://pubmed.ncbi.nlm.nih.gov/34225769/

**Comment by elifdogandar** [comment]
Hi,

I wanted to check splicing rates too. But apparently **'scv.utils.sum_var'** is not there anymore. Do you have an alternative way to check this? I would be grateful...
