### ISSUE TITLE
shape does not fit

### ISSUE THREAD

**Issue by wangjiawen2013** [theislab/scvelo#18]
Dear,
I am using scvelo to process my data. I have a mouse single cell dataset (9 samples and 40,000 cells in total), scvelo works well. But, for another mouse single cell dataset (2 samples and 4,000 cells in total), if I keep all the genes (about 18,000 genes), scvelo works well, while If filter some genes with adata = adata[:, filter_result.gene_subset] (about 2,000 genes are kept), the following error occurs. Could you help me find the cause ?

In [100]: scv.pp.moments(adata)
computing neighbors
    finished (0:00:04.18) --> added to `.uns['neighbors']`
    'distances', weighted adjacency matrix
    'connectivities', weighted adjacency matrix
computing moments based on connectivities
filtered out 1 cells that have less than 1 counts
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-100-5e6c0c5149c1> in <module>()
----> 1 scv.pp.moments(adata)

~/bin/miniconda3/lib/python3.6/site-packages/scvelo/preprocessing/moments.py in moments(data, n_neighbors, n_pcs, mode, use_rep, recurse_neighbors, renormalize, plot, copy)
     58 
     59     logg.info('computing moments based on ' + str(mode), r=True)
---> 60     normalize_layers(adata)
     61 
     62     connectivities = get_connectivities(adata, mode, recurse_neighbors=recurse_neighbors)

~/bin/miniconda3/lib/python3.6/site-packages/scvelo/preprocessing/utils.py in normalize_layers(data, layers, by_total_size, max_proportion_per_cell, copy)
    277             if max_proportion_per_cell is not None and (0 < max_proportion_per_cell < 1):
    278                 counts_per_cell = counts_per_cell_quantile(adata.X, max_proportion_per_cell, counts_per_cell)
--> 279             adata.layers[layer] = normalize_per_cell(adata.layers[layer], None, counts_per_cell, copy=True)
    280     return adata if copy else None
    281 

~/bin/miniconda3/lib/python3.6/site-packages/anndata/layers.py in __setitem__(self, key, value)
     58         else:
     59             if value.shape != self._adata.shape:
---> 60                 raise ValueError('Shape does not fit.')
     61             self._layers[key] = value
     62 

ValueError: Shape does not fit.

**Comment by stefanpeidli** [comment]
Hi,
I was able to recreate that error. I think it is because `normalize_per_cell` within `scv.pp.moments(adata)` tries to filter out cells and therby tries to change the size of the overall adata object, giving us this shape mismatch error. In my cases this filtering only affected the unspliced layer. As a workaround: 
After your custom gene filtering, try running
`import scanpy.api as sc`
`subset, counts = sc.pp.filter_cells(adata.layers['unspliced'], min_counts=1)`
`adata = adata[subset, :]`
and then try `scv.pp.moments(adata)`. This way there is no need for filtering in `scv.pp.moments(adata)` and thus no need for reshaping.

This seems to be a scVelo bug though, we will work it out soon. Thanks a lot for sharing!

**Comment by VolkerBergen** [comment]
Thanks for this important comment. Cells with zero counts are now handled correctly.
