### ISSUE TITLE
about gene for velocity

### ISSUE THREAD

**Issue by hahia** [theislab/scvelo#216]
This is a amazing package
I'm a new user of python and scVelo. I have some naive questions, 
I have 2421 cells dropseq data and annotate spliced/unspliced with velocyto. 

just capture 8% unspliced

An average of about 800 genes were detected of dropseq data.

I use scVelo to velocity analysis, use stochastic and dynamic model.

```
scv.pp.filter_and_normalize(adata, min_shared_counts=20, n_top_genes=500)
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
scv.tl.velocity(adata,mode='stochastic')
scv.tl.velocity_graph(adata)
```

`print(adata.var.velocity_genes.sum())`
74

scv.pl.velocity_embedding_stream(adata, basis='umap',color='cluster')
![image](https://user-images.githubusercontent.com/49113803/84484066-d419fc00-accc-11ea-9240-deb910959eea.png)

####dynamic model
scv.tl.recover_dynamics(adata)
scv.tl.velocity(adata, mode='dynamical')
scv.tl.velocity_graph(adata)

`print(adata.var.velocity_genes.sum())`
62

scv.pl.velocity_embedding_stream(adata, basis='umap',color='cluster')
![image](https://user-images.githubusercontent.com/49113803/84484090-daa87380-accc-11ea-82aa-0fa49a052b7b.png)

```
top_genes = adata.var['fit_likelihood'].sort_values(ascending=False).index[:300]
scv.pl.scatter(adata, basis=top_genes[:10], frameon=False, ncols=5,color='cluster')
```
![image](https://user-images.githubusercontent.com/49113803/84484851-e8122d80-accd-11ea-83db-74f1f56be0dd.png)

```
counts_s = scv.utils.sum_var(adata.layers['spliced'])
counts_u = scv.utils.sum_var(adata.layers['unspliced'])
fractions_u = counts_u / (counts_s + counts_u)
scv.pl.scatter(adata, color=fractions_u, smooth=True)
```
![image](https://user-images.githubusercontent.com/49113803/84484994-18f26280-acce-11ea-9319-b95bbbfc56f8.png)

1.Is around 100 genes enough for infer cell next state?
2.there have diferent direction in cluster 6, 9, 3, which we care about. which one is right?

**Comment by WeilerP** [comment]
>1.Is around 100 genes enough for infer cell next state?

100 seems a bit low but the number of genes needed depends on the dataset, in general. As outlined in this [supplementary material](https://static-content.springer.com/esm/art%3A10.1038%2Fs41587-020-0591-3/MediaObjects/41587_2020_591_MOESM1_ESM.pdf), you can see that already 30 genes explain a large portion of the dynamics in the dentate gyrus dataset.

>2.there have diferent direction in cluster 6, 9, 3, which we care about. which one is right?

Based on the phase portraits of the genes with the highest likelihood it seems that your dataset does not provide enough information to infer dynamics. To be more concise: The phase portraits do not exhibit the characteristic almond/football shape. Take FOLH1 for example: An up- and down-regulation has been fitted. However, you could just as easily fit only an up- or down regulation since the phase portrait is linear.

**Comment by JohnGenome** [comment]
Hi @WeilerP , taking that phase portraits of many velocity genes are lack of information (perhaps linear or random), if it's a possiable solution to manully select the genes with characteristic almond/football pattern (via `var.velocity_genes`) and rerun the `velocity_graph()`?
It sounds like to introduce subjective bias, but the result direction is just as we expect.
I'll move to a new issue and show more information if you want.

**Comment by WeilerP** [comment]
@JohnGenome, yes that would be a solution. However, just be aware that observing (part of) a desirable phase portrait does not imply correct inference (w.r.t known biology) as model assumptions could still be violated. See _e.g._ [this](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02414-y) example where transcriptional bursts are observed (_i.e._ the assumption of approx. constant rates is violated).
