### ISSUE TITLE
terminal velocity identified 0 region of root cells 

### ISSUE THREAD

**Issue by noorisotoudeh** [theislab/scvelo#257]
Hi scVelo team,
I am working with scvelo on my samples and I am looking for roots and ends. but for some of the samples it can't identify any root region with the following message:
==============================
computing terminal states
    identified 0 region of root cells and 1 region of end points 
==============================
I know that it depends on the transition matrix and in this case it means that there is no eigenvalue equal to 1 to find the corresponding eigenvector as roots. My question is that is there any way to find what is wrong about my samples? why I don't have any root cells with probability equal to 1? is this because of spliced/Unspliced ration? 

Thanks,

Noori

**Comment by noorisotoudeh** [comment]
I used 
scv.tl.velocity_graph(adata, mode_neighbors='connectivities')
from https://github.com/theislab/scvelo/issues/223 and it identified one root but the result doesn't make sense. As the following picture shows root and ends are distributed while it says one root and one end point.
![image](https://user-images.githubusercontent.com/62612418/88564731-91547f00-d001-11ea-8a04-6cde689f4534.png)

**Comment by VolkerBergen** [comment]
This yields probabilities of being classified/identified as a root cell. Since the velocities are relatively fuzzy, the root cell probabilities become quite fuzzy as well. Generally, to understand the vector field and the downstream application such as root cell identification it is necessarily to look into gene-dynamics (phase portaits of e.g. top-likelihood genes), to find supportive genes.

**Comment by noorisotoudeh** [comment]
Hi VolkerBergen,
thanks for your answer and your nice package. I am really enjoying using it. 
I realized that by playing with the three parameters, n_top_genes, n_pcs and  n_neighbors the location and number of root/ends will be changed. So, how can I say which one is true. Do I have to look at top-likelihood genes matrix?
but I don't want to use top-likelihood genes matrix produced by scvelo. I want to use the identified root cells and end points cells  and then I will use those cells to perform findmarker genes by scran.
that's why I am curious about the number of roots and ends.

Thanks,

Noori

**Comment by WeilerP** [comment]
@noorisotoudeh, there is no definite/quantifiable criterion to say which identified set of root/terminal states is correct without any prior biological insight. In #462, for example, the true direction is known but scVelo cannot infer it due to the data. In this case, identified root/terminal states would be switched compared to the ground truth.
