### ISSUE TITLE
Loading mnn-corrected coordinates as X_pca for batch correction?

### ISSUE THREAD

**Issue by skannan4** [theislab/scvelo#268]
Hi scvelo team! This may be related to multiple previous issues regarding batch effects, but I'm trying to figure out if this particular approach is appropriate. I'm working with a dataset consisting of multiple timepoints where the libraries were prepared in three batches (each batch containing a mix of the timepoints). I initially analyzed these in R with Monocle3, which uses fastMNN for batch correction. Rather than directly correcting the data in high dimensions, this gives a corrected low dimension output. (This analysis was done on the combined spliced/unspliced counts). This subsequently enabled me to generate a trajectory in UMAP space.

To perform the velocity analysis, I loaded in the spliced counts as adata.X and as a layer, and the unspliced as a layer. I added the Monocle3 UMAP as an obsm. Lastly, I loaded the fastMNN low dimension coordinates as "X_pca" in obsm, so that during the pp.moments step, these corrected coordinates would be used. Thus, adata.X is actually not "corrected" in any way, just the neighbours can be more accurately identified during pp.moments. Is this an appropriate way for handling batch correction, or would you have a different recommendation? Not exactly sure how python-based batch correction works, especially since in this case I'm porting in everything from R.

**Comment by VolkerBergen** [comment]
At the current state, as there doesn't exist any benchmarked approach of batch-correcting both modalities, I think your approach is a valid way of doing so. I'd however validate (e.g. on the top-likelihood genes) what kind of an effect the correction has on the counts and how un/spliced relate after correction. Using your approach I'd expect batches to overlap more as they are averaged together through moments computed on the corrected neighbor graph, on the other hand this might remove some signal due to averaging between batches. Thus, I'd recommend to look into phase portraits, how the relation between un/spliced changes and whether it is batch effects are correctly removed and/or whether the signal from splicing kinetic gets lost.

As for python-based methods, you can check out [scanpy](https://scanpy.readthedocs.io/en/stable/external/index.html)'s batch correction and data integration methods (for me, bbknn mostly did a good job).
