### ISSUE TITLE
Likelihood equation in paper (eq. (7))

### ISSUE THREAD

**Issue by NajwaLaabid** [theislab/scvelo#287]
The likelihood equation given in the paper seems to have a misplaced 'n'. 
This is the original equation:
<img width="687" alt="Screen Shot 2020-09-10 at 16 35 11" src="https://user-images.githubusercontent.com/17838639/94362338-3f90a980-00c3-11eb-801f-a059fd2d071c.png">

This is what I believe a regular likelihood equation should look like ([source](https://www.statlect.com/fundamentals-of-statistics/normal-distribution-maximum-likelihood)):
<img width="1104" alt="Screen Shot 2020-09-10 at 16 42 32" src="https://user-images.githubusercontent.com/17838639/94362366-6353ef80-00c3-11eb-8160-e94b0dde9fc7.png">

The 1/n in the exponential term should belong to the fraction term before it (then in the first term of the log expression). It comes from the product in the definition of likelihood. Am I missing something here?

**Comment by VolkerBergen** [comment]
Thanks for spotting this. In terms of optimization, it is equivalent b/c the log-likelihood equation in the manuscript is simply scaled by 1/n (which corresponds to the n-th power in the actual likelihood). The division by n is due to better numerical stability (with the same rationale why ppl often use the mean squared error instead of the actual squared error).

**Comment by NajwaLaabid** [comment]
Great, thank you for the clarification!
