### ISSUE TITLE
Multiple scVelo files

### ISSUE THREAD

**Issue by 5rycaa** [theislab/scvelo#314]
Hi,

I have a clarification question considering multiple files as a part of one analysis. I've read few of the similar questions/issues, but I haven't really stumbled upon a suggested way to do it, and hence seeking your guidance. In my analysis, I am using dropEst to get the counts, load them in R, to a Seurat object, export it as a loom file and run scVelo. However, this is my pipeline for a single file, and now I am wondering at which level should I merge them for the sake of analyzing it all together?

My suggestions/ideas would be:
1. reading counts (from each file) in Seurat object --> exporting a loom file per file --> run scVelo per file --> merge outputs
2. reading counts (from each file) in Seurat object --> exporting a loom file per file --> merge looms --> run scVelo
3. reading counts (from each file) in Seurat object --> merging Seurat objects --> exporting a loom file  --> run scVelo

I haven't tested any of them yet, as I am assuming that some might lead to lots of errors, some might be totally unfeasible, and I could also assume that depending on what you input, the final result will be totally different.

Thanks!

**Comment by Laura19993** [comment]
Any suggestions towards this? Would be also interested what would be the best option

**Comment by WeilerP** [comment]
> 1. reading counts (from each file) in Seurat object --> exporting a loom file per file --> run scVelo per file --> merge outputs

This will merge individual analyses into a single object. I do not believe that this is what you want to do as you will not consider any "across-file information" in your velocity analysis. Suppose e.g. each file contains the count matrices of a single patient. This pipeline will then run the velocity for each patient individually. A couple of red flags: You will not have a neighbor graph for your final, merged data. The UMAP embedding you find will also not contain any "across file information". I am not even sure how you would interpret this new UMAP embedding since it does not capture the underlying topology of the entire data. Instead you combined different embeddings calculated on different neighbor graphs.

> 2. reading counts (from each file) in Seurat object --> exporting a loom file per file --> merge looms --> run scVelo
> 3. reading counts (from each file) in Seurat object --> merging Seurat objects --> exporting a loom file  --> run scVelo

You should merge the different datasets prior to you velocity analysis if you want to take all the available information into account. Sorry, I am currently missing how these two approaches differ.
