### ISSUE TITLE
Group constraints for aggregated samples?

### ISSUE THREAD

**Issue by dpcook** [theislab/scvelo#34]
Hi there,

I was wondering if there was a way (or if it is necessary) to manage situations when the data is aggregated data from multiple samples, where neighbouring cells in PC space may not have the same properties due to different sample conditions (eg. differentiation time course experiments, where the lagging cells of one time point may by neighbours to fast-responding cells of the previous time point). 

I know Velocyto has problems with this when using default settings because of knn imputation (a group_constrain parameter in the knn_imputation function deals with this though), but I'm not super familiar with the differences between scvelo and Velocyto, so it may not be relevant. 

Any help is appreciated!

David

**Comment by VolkerBergen** [comment]
Hi David, 

good point and indeed not an easy one.

For time-resolved data, I'd actually hope to have sort of a continuous representation, thus a lagging t1-cell neighbouring a fast-responding t0-cell does not harm. In such scenarios, my velocities have usually confirmed the time course directionality.

However, when sampled time points have completely distinct representation because of technical effects, it is not straightforward to deal with this. We'd need to apply correction in such a way that the transformation of our count data is applied exactly the same way for both spliced and unspliced. Not all batch effect correction methods provide that.

You can check multisample-bias as follows: First run `tl.velocity` on samples separately by setting the attribute `groupby='sample'`(exemplary denotation). When further setting `groups='sample_name'` it will only estimate velocities on one specific sample. 

Visualize. Then run the same on all jointly and see whether any of the embedded velocities changes.
