### ISSUE TITLE
The (un)spliced information is different from the phase diagram

### ISSUE THREAD

**Issue by yuehhua** [theislab/scvelo#384]
Thank you for making this great package. I want to leverage the advantage and build my own model.
Thus, I need spliced and unspliced gene expression, so I found `adata.layers['spliced']` and `adata.layers['unspliced']`.
First, I want to verify these values. As my expectation, it should look like this.

![Imgur](https://i.imgur.com/QwKIwro.png)

I tried to plot phase portrait myself. I try the Rps3 gene in the top 4th.

![Imgur](https://i.imgur.com/DAZL3R3.png)

Apparently, it doesn't satisfy my expectation.

Then, I try other values in `adata` and I found `adata.layers['Ms']` and `adata.layers['Mu']`.

![Imgur](https://i.imgur.com/tx7KvOE.png)

This is my expectation!

I wonder what is their difference? In manual, everything direct to `adata.layers['spliced']` and `adata.layers['unspliced']` but not `adata.layers['Ms']` and `adata.layers['Mu']`.

What is the meaning of `adata.layers['Ms']` and `adata.layers['Mu']`?
I read the documentation of `scvelo.pp.moments` and it say that it is the first moment of (un)spliced expression. 
I expect the moment refers to the statistical first moment -- that is, the mean value.
Am I right?

#### Versions
scvelo==0.2.0  scanpy==1.5.1  anndata==0.7.3  loompy==3.0.6  numpy==1.18.4  scipy==1.4.1  matplotlib==3.2.1  sklearn==0.23.1  pandas==1.0.3

**Comment by WeilerP** [comment]
Since raw data is usually noisy and sparse, we impute it and, following, study phase portraits, infer model parameters, etc. As you already mentioned correctly, the slots `'Mu'` and `'Ms'` are (first) moments of unspliced and spliced counts. The first moments are given by the average gene expression of the *k* nearest neighbors of a cell. As such, they can be interpreted as the mean value of a local neighbourhood.

**Comment by yuehhua** [comment]
Thank you so much!
