### ISSUE TITLE
should I use precomputed umap embedding/clustering or compute it with scvelo?

### ISSUE THREAD

**Issue by chansigit** [theislab/scvelo#395]
I always used umap and clustering computed by scanpy based on expressional profiles. And I noticed that scVelo also provided clustering and umap embedding computation.

I guess the scvelo's umap/clustering is based on the velocity neighbors so might be better for visualization and lineage identification.

should I use the original cluster/umap or recompute it with scVelo?

**Comment by VolkerBergen** [comment]
`umap`, `leiden`, `louvain` in `scanpy`/`scvelo` are equivalently computed on the actual neighbor graph (transcriptome/pca-based, not velocity-based), thus using the precomputed ones is fine.

**Comment by dawe** [comment]
Following the initial question, what would be the strategy to calculate the embeddings starting from the velocity graph?

**Comment by VolkerBergen** [comment]
If you want to incorporate velocity information, we've had a first suggestion of a velo-based diffusion map [here](https://github.com/theislab/scvelo/blob/1659cc8e00a45fcf87cd80a7013aae5531744613/scvelo/tools/velocity_pseudotime.py#L59). Otherwise, you cold consider an autoencoder-based approach for a joint latent representation of un/spliced.

**Comment by dawe** [comment]
Thanks. As for the second choice, a few weeks ago I have been trying MOFA+ (not AE-based) on both layers and I ended up with teardrop-like patterns which nicely correlated with latent time from the dynamical modelling. I didn't pay attention then, I wonder if instead was a general result. I hope I can find time to investigate this further
