### ISSUE TITLE
Velocity changes after update to 0.1.15

### ISSUE THREAD

**Issue by JonasMir** [theislab/scvelo#42]
Hi Volker,
I just wondered why the RNA velocity flows have changed in my case (not entirely, but significantly) after I have updated scvelo to version 0.1.15 without having done any further changes. Did you change/improve anything that could explain this?
Best, Jonas

**Comment by VolkerBergen** [comment]
Hi Jonas,
there have been one or two changes such as setting extreme quantile as default (instead of simple fit).
What was your previous version?

**Comment by JonasMir** [comment]
Ok, I see. My previous version is from October 2018. This is a quite imprecise answer but I don't know how to get this out of pip...

**Comment by VolkerBergen** [comment]
You can get the version via `scv.logging.print_version()`

I see that I have made the 'extreme quantile fit' as default in December (being more robust and better at capturing steady states). You can run it on all data (instead of quantiles) via `scv.tl.velocity(adata, perc=None)`.

**Comment by JonasMir** [comment]
Thanks, this is the answer! Setting perc=None reproduces my old results. Though my system (T cells within acute infection) definitely is not in steady state - which option would you recommend here?

**Comment by VolkerBergen** [comment]
It's all approximate since a steady-state population is the underlying assumption. Setting `perc` to extreme quantiles would usually capture the steady states better (or at least be more conservative if no steady state is sampled). You could examine the phase portraits (`pl.velocity`) for some of your favorite genes and check out the difference when using simple fit vs. extreme quantile fit.

Soon (~March/April) a novel method (capturing the full stochastic dynamics) will be released and published, that is not subject to the steady state assumption anymore.

**Comment by SamueleSoraggi** [comment]
Looking forward to play around with the method and read the publication!!! Keep the good work up ;)
