### ISSUE TITLE
How to save the figure from scv.pl.proportions()?

### ISSUE THREAD

**Issue by zhangjiaobxy** [theislab/scvelo#421]
Thanks for developing this awesome package. I have a minor question.

I didn't find a `save` parameter from `scv.pl.proportions()`. Is there a way that I can save the figure which is generated from `scv.pl.proportions()`?

I am using scVelo version 0.2.3.

Thanks a lot!

**Comment by VolkerBergen** [comment]
`scv.pl.proportions` has no save option yet. Will implement that for the next release. As workaround you can do:
```
ax = scv.pl.proportions(adata, show=False)
scv.pl.utils.savefig_or_show(save='proportions.pdf')
```

**Comment by zhangjiaobxy** [comment]
> `scv.pl.proportions` has no save option yet. Will implement that for the next release. As workaround you can do:
> 
> ```
> ax = scv.pl.proportions(adata, show=False)
> scv.pl.utils.savefig_or_show(save='proportions.pdf')
> ```

Thanks @VolkerBergen ! I can save the figure in this way! Thanks for your help!

**Comment by AAA-3** [comment]
> `scv.pl.proportions` has no save option yet. Will implement that for the next release. As workaround you can do:
> 
> ```
> ax = scv.pl.proportions(adata, show=False)
> scv.pl.utils.savefig_or_show(save='proportions.pdf')
> ```

Is there a way to modify the dimensions in any way? I tried setting them in `scv.set_figure_params('scvelo',dpi=300, dpi_save=500, figsize=[1200,1200], format='png')` but the saved files do not seem to change. I ask because the saved image has overlapping text:
![scvelo_KO_proportions](https://user-images.githubusercontent.com/68068335/130456957-8de73471-5193-4ae1-9c39-343a5db59ff2.png)
