### ISSUE TITLE
Make streamline arrow size adjustable

### ISSUE THREAD

**Issue by rorymaizels** [theislab/scvelo#486]
I am preparing a velocity streamline plot for publication, but the default arrow size in scv.pl.velocity_embedding_stream are too small to be seen properly within the figure. Adjusting `linewidth` leads to wider lines but doesn't affect the arrow head (example picture below). Currently we are looking at having to manually draw illustrative arrows over the plot, which somewhat defeats the point of scvelo's plotting functionality.

Could `arrowsize` be included as an argument to pas to `stream_kwargs` on line 201 of `velocity_embedding_stream.py`, to then pass on to ax.streamplot?

If there are any other options for increasing arrow size let me know!

<img width="587" alt="Screenshot 2021-06-04 at 11 17 19" src="https://user-images.githubusercontent.com/29228970/120788781-a276f200-c528-11eb-8412-15a3c6b80a51.png">

#### Versions:

> scvelo==0.2.2  scanpy==1.6.0  anndata==0.7.5  loompy==3.0.6  numpy==1.19.4  scipy==1.5.4  matplotlib==3.3.3  sklearn==0.23.2  pandas==1.2.3

**Comment by WeilerP** [comment]
@rorymaizels, will add the possibility to specify custom arguments to be passed to `matplotlib.pyplot.streamplot`.

Instead of drawing the arrows, manually, you can clone `scvelo`, open a new branch (either based on a tag or `scvelo@develop`) and update `scvelo.plotting.velocity_embedding_stream.py:velocity_embedding_stream` to your needs.

As a general note: Please only tag issues with the `bug` label if there really is a bug. This is a feature request.

**Comment by WeilerP** [comment]
Closed via #492.
