### ISSUE TITLE
Detect if adata.X is log normalised or not.

### ISSUE THREAD

**Issue by saksham219** [theislab/scvelo#49]
Hi

I wanted to know how the check 'Did not modify X as it looks preprocessed already' is working. In the code it is comparing counts of spliced and X. 
`log_advised = np.allclose(adata.X[:10].sum(), adata.layers['spliced'][:10].sum())`

Can you comment on why X would be log normalised if these counts are equal?

**Comment by VolkerBergen** [comment]
First of all, when reading your data, `adata.X` and `adata.layers['spliced']` are equal. Normalization and filtering is applied equally to `X` as well as spliced counts. In that line, it checks whether `X` and spliced counts are equal (which is usually the case unless you have an already preprocessed `X` from former analysis). Per default log-transformation is applied (as it is usually done in single cell analysis in oder to make variation in your data relative instead of absolut, thereby variation comes from the data and not from outliers), but only to `X`. Spliced/unspliced counts are not log-transformed.

If needed, I can give a little more clarification on why to log-transform your data. You could just compare PCA before and after log-transform. That shows how variation is potentially dominated by outliers in raw data. Log-transform, however, is a general preprocessing procedure and not velocity-specific.

**Comment by saksham219** [comment]
Thank you for the clarification. I am wondering what happens in a case where `adata.X` and adata.layers['spliced'] are not equal and adata.X is preprocessed because of coming from a different analyses, but the preprocessing is not a log transformation. Should checks be included in such a case to detect if adata.X is on a log scale?

**Comment by VolkerBergen** [comment]
It is not straightforward to check whether `X` lives on log scale already, as many follow-up transformations such as scaling to unit variance won't make it traceable anymore. But maybe you have an idea, how to add a simple check?

As this is not 'velocity'-specific, but part of the general preprocessing pipeline, I guess it is ok to leave this to the user. The PCA would in most cases be pulled apart, if it is computed on non-log data. Here, at the latest, the user hopefully realizes that something might be missing. Finally, it is not required to logarithmize your data (even if common routine), as long you make sure your variance in the data is not solely governed by outliers.

**Comment by saksham219** [comment]
A simple method can check if data was log normalised or data was scaled to unit variance.

1. For checking if data is log scaled we can simply take the range of counts ; max(X) - min(X). If this range is greater than 100(another assumption) it can be said that the counts have not been log transformed
I agree with your point that if the data was scaled to a unit variance beforehand, this method would fail.

**Comment by VolkerBergen** [comment]
Would be quite heuristic and covering only few cases. Since log is common preprocessing procedure, I'd assume that the user has done so if he merges his pre-analysed data.

The most important cases are already covered in `filter_and_normalize`, see https://github.com/theislab/scvelo/blob/d64a55d455cfaab0e61c8c41b7528216263720cd/scvelo/preprocessing/utils.py#L410
