### ISSUE TITLE
Bug appears when I import scvelo as scv

### ISSUE THREAD

**Issue by linscnano** [theislab/scvelo#685]
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.

```python
# paste your code here, if applicable
```

<details>

<summary> Error output </summary>

```pytb
# paste the error output here, if applicable
```
</details>

<details> <summary> Versions </summary>

```pytb
# paste the ouput of scv.logging.print_versions() here
```
</details>

**Comment by WeilerP** [comment]
@linscnano, please either open a new issue providing a reasonable title, all info asked for in the issue template and a description of when you encounter this error (e.g. OS, when importing it from terminal or an editor or JupyterLab) or reopen this issue and update title and issue description accordingly.

FYI: I do not encounter the issue when importing scvelo but only when running `scv.logging.print_versions()`. As suggested by the error message, this is caused by XMLRPC search being permanently being disabled in the future. The error is caused by calling `check_output` from `subprocess` [here](https://github.com/theislab/scvelo/blob/1805ab4a72d3f34496f0ef246500a159f619d3a2/scvelo/logging.py#L181).
