### ISSUE TITLE
Stream plot color limits

### ISSUE THREAD

**Issue by TobiTekath** [theislab/scvelo#96]
Hi Volker,
I would like to create a stream plot with consistent color limits across multiple datasets.

The stream plot call looks like:

```
import matplotlib.pyplot as plt
x=scv.pl.velocity_embedding_stream(adata, basis='umap', color='my_attr', color_map="viridis", legend_loc='right margin', show=False)
```
Unfortunately the returned AxesSubplot does not seem to have a `set_clim()` function and I am not able to set it as the current artist via `plt.gci()`. 
In version `0.1.19.dev47+8d111c8` it simply worked to call for example `plt.clim(0,1)` to change the color limits after the above plotting command. In `0.1.24.dev6+geb35fe8` this does not work anymore.
Would it be possible to set the desired color limits in the stream plot call, or to hint me in the direction how to set it manually.

I am not a matplotlib expert, so I am very sorry if I missed a trivial way to accomplish my goal.

Thanks a lot!

**Comment by VolkerBergen** [comment]
Hi Tobi, 
indeed. @stefanpeidli can you have a look, why clim breaks?

If that helps as workaround, in `scatter` you can set `vmin` and `vmax`.

**Comment by stefanpeidli** [comment]
Hi Tobi,

you are right, it is not possible anymore to set the color limits in stream plots. This is because we changed the way figures are handled internally. We will fix this soon by adding the same `vmin` and `vmax` arguments which the `scatter` plot function already has.

As a workaround I woud suggest to separate the scatter and the stream plot functionalities by making two calls:
```
from scvelo.plotting.utils import default_size
size = 4 * default_size(adata)
x=scv.pl.scatter(adata, basis='umap', color='my_attr',  color_map="viridis", legend_loc='right margin',
                                   show=False, alpha=.1, size=size, vmin=10, vmax=30)
x2=scv.pl.velocity_embedding_stream(adata, basis='umap', color='my_attr', color_map="viridis", 
                                   legend_loc='right margin', show=False, alpha=0, ax=x, colorbar=False)
```
The limits of the colormap can then be adjusted using the `vmin` and `vmax` arguments in `scatter`, as Volker already suggested.

Hope this helps!

**Comment by TobiTekath** [comment]
Thanks Volker and Stefan for the quick reply. The workaround works just fine.

**Comment by VolkerBergen** [comment]
You can now use vmin, vmax, vmid etc. within any velocity plotting module.
